In [1]:
import os
import pandas as pd
import numpy as np

In [3]:
beh = pd.read_csv('./train/训练数据集_beh.csv')

beh['day'] = beh['page_tm'].apply(lambda x: x.split(' ')[0])
beh['time'] = beh['page_tm'].apply(lambda x: x.split(' ')[1])
del beh['page_tm']

In [17]:
beh[beh['id'] == 'U10001'].head(50)

            id  flag page_no        day   time
433404  U10001     0     CQE  2019/6/11  17:16
433405  U10001     0     TRN  2019/6/16  12:28
433406  U10001     0     CQA   2019/6/3  15:31
433407  U10001     0     XAI  2019/6/16  12:28
433408  U10001     0     CQE  2019/6/21  21:04
433409  U10001     0     CQE  2019/6/17  16:23
433410  U10001     0     CQE  2019/6/17  16:23
433411  U10001     0     TRN  2019/6/16  12:27
433412  U10001     0     CQA  2019/6/16  12:26
433413  U10001     0     TRN  2019/6/16  12:27
433414  U10001     0     CQE  2019/6/28   9:09
433415  U10001     0     CQA  2019/6/26  21:57
433416  U10001     0     XAI   2019/6/3  15:31
433417  U10001     0     TRN  2019/6/28   9:11
433418  U10001     0     CQE  2019/6/21  21:05
433419  U10001     0     FTR  2019/6/26  21:57
433420  U10001     0     CQE  2019/6/16  12:28
433421  U10001     0     FTR  2019/6/28   9:11
433422  U10001     0     CQE  2019/6/26  21:58
433423  U10001     0     BWE   2019/6/3  15:31
433424  U10001     0     FTR   2019/6/7  17:44
433425  U10001     0     CQC  2019/6/17  16:23
433426  U10001     0     CQA   2019/6/3  15:31
433427  U10001     0     CQE   2019/6/3  15:31
433428  U10001     0     CQA  2019/6/21  21:03
433429  U10001     0     CQA  2019/6/28   9:09
433430  U10001     0     CQA  2019/6/17  16:22
433431  U10001     0     FTR  2019/6/28   9:10
433432  U10001     0     TRN   2019/6/7  17:43
433433  U10001     0     FTR  2019/6/16  12:27
433434  U10001     0     TRN  2019/6/21  21:04
433435  U10001     0     CQE  2019/6/11  17:12
433436  U10001     0     XAI   2019/6/3  15:31
433437  U10001     0     FTR  2019/6/11  17:13
433438  U10001     0     TRN  2019/6/11  17:15
433439  U10001     0     CQE   2019/6/3  15:31
433440  U10001     0     AAO  2019/6/17  16:23
433441  U10001     0     TRN  2019/6/26  21:57
433442  U10001     0     CQE  2019/6/26  21:57
433443  U10001     0     TRN  2019/6/26  21:58
433444  U10001     0     CQE  2019/6/16  12:26
433445  U10001     0     XAI  2019/6/16  12:28
433446  U10001     0     CQA  2019/6/11  17:12
433447  U10001     0     CQE  2019/6/16  12:26
433448  U10001     0     XAI   2019/6/3  15:32
433449  U10001     0     CQE  2019/6/16  12:28
433450  U10001     0     FTR  2019/6/16  12:26
433451  U10001     0     AAO  2019/6/16  12:26
433452  U10001     0     CQE  2019/6/16  12:28
433453  U10001     0     CQE  2019/6/21  21:06

In [ ]:
info = beh.groupby(['id', 'page_no', 'day']).agg({'flag': 'count'})
one_id = info[info.index.get_level_values('id') == 'U10001']

In [42]:
one_id.groupby(level=0).apply(lambda x: x / float(x.sum()))

                              flag
id     page_no day
U10001 AAO     2019/6/16  0.027778
               2019/6/17  0.027778
       BWA     2019/6/3   0.027778
       BWE     2019/6/3   0.013889
       CQA     2019/6/11  0.013889
               2019/6/16  0.027778
               2019/6/17  0.013889
               2019/6/21  0.013889
               2019/6/24  0.013889
               2019/6/26  0.013889
               2019/6/28  0.013889
               2019/6/3   0.041667
               2019/6/7   0.013889
       CQC     2019/6/17  0.013889
       CQE     2019/6/11  0.027778
               2019/6/16  0.083333
               2019/6/17  0.027778
               2019/6/21  0.055556
               2019/6/26  0.027778
               2019/6/28  0.027778
               2019/6/3   0.041667
               2019/6/7   0.027778
       FTR     2019/6/11  0.013889
               2019/6/16  0.027778
               2019/6/21  0.013889
               2019/6/26  0.013889
               2019/6/28  0.027778
               2019/6/7   0.013889
       TRN     2019/6/11  0.027778
               2019/6/16  0.055556
               2019/6/21  0.041667
               2019/6/26  0.027778
               2019/6/28  0.041667
               2019/6/7   0.027778
       XAI     2019/6/16  0.027778
               2019/6/3   0.041667